# Generated by Django 4.1.3 on 2022-11-15 03:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('documento', models.IntegerField()),
                ('domicilio', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('estado_civil', models.CharField(choices=[('Casado/a', 'CASADO/A'), ('Soltero/a', 'SOLTERO/A'), ('Divociado/a', 'DIVORCIADO/A'), ('Viudo/a', 'VIUDO/A')], max_length=30)),
                ('religion', models.CharField(max_length=20)),
                ('fehca_de_nacimiento', models.DateField()),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PacientesApp.historiaclinica')),
            ],
        ),
    ]
