# Generated by Django 4.1.3 on 2022-11-23 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('estado_civil', models.CharField(choices=[('Casado/a', 'CASADO/A'), ('Soltero/a', 'SOLTERO/A'), ('Divociado/a', 'DIVORCIADO/A'), ('Viudo/a', 'VIUDO/A')], max_length=30)),
                ('religion', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('doctor', models.ManyToManyField(related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('paciente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='PacientesApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
