# Generated by Django 4.1.3 on 2022-11-17 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PacientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.ManyToManyField(related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
