# Generated by Django 4.1.3 on 2022-11-18 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PacientesApp', '0002_paciente_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='PacientesApp.paciente'),
        ),
    ]
