# Generated by Django 4.1.3 on 2022-11-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PacientesApp', '0002_alter_consulta_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to=settings.AUTH_USER_MODEL),
        ),
    ]
