# Generated by Django 4.1.3 on 2022-11-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PacientesApp', '0002_alter_historiaclinica_historia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fehca_de_nacimiento',
            new_name='fecha_de_nacimiento',
        ),
    ]
