# Generated by Django 4.1.3 on 2022-11-12 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('obra_social', models.CharField(max_length=30)),
                ('historia_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.historiaclinica')),
            ],
        ),
    ]
