# Generated by Django 4.1.3 on 2023-01-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
