# Generated by Django 4.1.3 on 2023-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_blogposts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
