# Generated by Django 4.1.3 on 2022-11-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='meida/'),
        ),
    ]
