# Generated by Django 4.1.3 on 2022-11-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_alter_doctor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
