# Generated by Django 4.1.3 on 2022-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
