# Generated by Django 4.1.3 on 2022-11-12 21:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_doctor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
